# === Structured DB (docker) ===
spring.datasource.url=jdbc:postgresql://medsureai-db:5432/medsureai
spring.datasource.username=postgres
spring.datasource.password=Shreyas@sept12

spring.data.mongodb.uri=mongodb://medisureai-mongo:27017/medisure_documents
spring.rabbitmq.host=medisureai-rabbitmq
spring.rabbitmq.port=5672