spring.application.name=ragdemo

#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.init.pull-model-strategy=when_missing
#spring.ai.ollama.init.timeout=5m
#spring.ai.ollama.chat.options.model=llama3.2:3b
#spring.ai.ollama.embedding.options.model=nomic-embed-text
#spring.ai.vectorstore.pgvector.initialize-schema=true
#
## === Vector DB (existing) ===
#vector.datasource.url=jdbc:postgresql://localhost:5432/vectordb
#vector.datasource.username=testuser
#vector.datasource.password=testpwd
#vector.datasource.driver-class-name=org.postgresql.Driver


# === Structured DB (local) ===
spring.datasource.url=jdbc:postgresql://localhost:5432/medsureai
spring.datasource.username=$USER_NAME
spring.datasource.password=$PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


# Performance optimizations
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.index-type=HNSW

# File upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

logging.level.org.springframework.ai.vectorstore=DEBUG
